name: Run CI

on:
  pull_request:
    branches: [ master ]
    paths-ignore: [ 'website/**', 'docs/**', '*.md' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1-alpine3.23-sfw-dev
      options: --cpus 1
    steps:
      - run: cargo check
      - run: cargo test

  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    container:
      image: node:26-alpine-sfw-ent-dev
      options: --cpus 1
    steps:
      - run: yarn run check